package com.codereview.aicodereviewer.service;

import com.codereview.aicodereviewer.model.CodeIssue;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;

/**
 * Service to post review comments on GitHub
 * Day 11: Post AI feedback as PR comments
 */
@Service
@Slf4j
public class GitHubCommentService {

    @Value("${github.token:}")
    private String githubToken;

    private final RestTemplate restTemplate = new RestTemplate();

    /**
     * Post a review comment on a pull request
     *
     * @param owner Repository owner
     * @param repo Repository name
     * @param prNumber Pull request number
     * @param reviewBody The AI-generated review text
     * @return true if successful
     */
    public boolean postReviewComment(String owner, String repo, int prNumber, String reviewBody) {
        String url = String.format(
                "https://api.github.com/repos/%s/%s/issues/%d/comments",
                owner, repo, prNumber
        );

        log.info("Posting review comment to PR #{}", prNumber);

        // Format the comment nicely
        String formattedComment = formatReviewComment(reviewBody);

        HttpHeaders headers = createHeaders();
        Map<String, String> body = Map.of("body", formattedComment);
        HttpEntity<Map<String, String>> entity = new HttpEntity<>(body, headers);

        try {
            ResponseEntity<String> response = restTemplate.exchange(
                    url,
                    HttpMethod.POST,
                    entity,
                    String.class
            );

            log.info("✅ Comment posted successfully!");
            return response.getStatusCode().is2xxSuccessful();

        } catch (Exception e) {
            log.error("❌ Error posting comment: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Post an inline comment on a specific line of code
     *
     * @param owner Repository owner
     * @param repo Repository name
     * @param prNumber Pull request number
     * @param commitId The commit SHA
     * @param path File path
     * @param line Line number
     * @param comment Comment text
     */
    /**public boolean postInlineComment(String owner, String repo, int prNumber,
                                     String commitId, String path, int line, String comment) {
        String url = String.format(
                "https://api.github.com/repos/%s/%s/pulls/%d/comments",
                owner, repo, prNumber
        );

        log.info("Posting inline comment on {}:{}", path, line);

        HttpHeaders headers = createHeaders();
        Map<String, Object> body = Map.of(
                "body", comment,
                "commit_id", commitId,
                "path", path,
                "line", line
        );
        HttpEntity<Map<String, Object>> entity = new HttpEntity<>(body, headers);

        try {
            restTemplate.exchange(url, HttpMethod.POST, entity, String.class);
            return true;
        } catch (Exception e) {
            log.error("Error posting inline comment: {}", e.getMessage());
            return false;
        }
    }**/

    /**
     * Format the review comment with nice styling
     */
    private String formatReviewComment(String reviewBody) {
        return """
            ## 🤖 AI Code Review
            
            %s
            
            ---
            *Generated by AI Code Reviewer Bot*
            """.formatted(reviewBody);
    }

    /**
     * Create HTTP headers with GitHub token
     */
    private HttpHeaders createHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.set("Accept", "application/vnd.github+json");
        headers.set("X-GitHub-Api-Version", "2022-11-28");

        if (githubToken != null && !githubToken.isEmpty()) {
            headers.set("Authorization", "Bearer " + githubToken);
        }

        return headers;
    }

    /**
     * Post an inline comment on a specific line of code in a PR
     * This creates a "review comment" that appears directly on the code
     *
     * @param owner Repository owner
     * @param repo Repository name
     * @param prNumber Pull request number
     * @param commitSha The SHA of the commit to comment on
     * @param issue The code issue with line number and description
     * @return true if comment posted successfully
     */
    public boolean postInlineComment(String owner, String repo, int prNumber,
                                     String commitSha, CodeIssue issue) {
        String url = String.format(
                "https://api.github.com/repos/%s/%s/pulls/%d/comments",
                owner, repo, prNumber
        );

        log.info("Posting inline comment on {}:{} for PR #{}",
                issue.getFileName(), issue.getLineNumber(), prNumber);

        try {
            // Build request body
            Map<String, Object> requestBody = new HashMap<>();
            requestBody.put("body", issue.toMarkdownComment());
            requestBody.put("commit_id", commitSha);
            requestBody.put("path", issue.getFileName());
            requestBody.put("line", issue.getLineNumber());
            requestBody.put("side", "RIGHT");  // RIGHT = new code, LEFT = old code

            // Make API call
            HttpHeaders headers = createHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);

            ResponseEntity<String> response = restTemplate.exchange(
                    url,
                    HttpMethod.POST,
                    entity,
                    String.class
            );

            boolean success = response.getStatusCode().is2xxSuccessful();
            if (success) {
                log.info("✅ Posted inline comment on line {}", issue.getLineNumber());
            } else {
                log.warn("⚠️ Failed to post inline comment: {}", response.getStatusCode());
            }

            return success;

        } catch (Exception e) {
            log.error("❌ Error posting inline comment: {}", e.getMessage());
            return false;
        }
    }

    /**
     * Post multiple inline comments for a list of issues
     *
     * @param owner Repository owner
     * @param repo Repository name
     * @param prNumber Pull request number
     * @param commitSha Commit SHA
     * @param issues List of code issues
     * @return Number of comments successfully posted
     */
    public int postInlineComments(String owner, String repo, int prNumber,
                                  String commitSha, List<CodeIssue> issues) {
        int successCount = 0;

        log.info("Posting {} inline comments for PR #{}", issues.size(), prNumber);

        for (CodeIssue issue : issues) {
            if (postInlineComment(owner, repo, prNumber, commitSha, issue)) {
                successCount++;
            }

            // Small delay to avoid rate limiting
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }

        log.info("Posted {}/{} inline comments successfully", successCount, issues.size());
        return successCount;
    }
}